# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/CodeCheckList',
                'doc_host': 'https://WM-SEMERU.github.io',
                'git_url': 'https://github.com/WM-SEMERU/CodeCheckList',
                'lib_path': 'CodeCheckList'},
  'syms': {'CodeCheckList.core': {'CodeCheckList.core.foo': ('core.html#foo', 'CodeCheckList/core.py')}}}