# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/wrapper.ipynb.

# %% auto 0
__all__ = ['TimeoutException', 'break_after']

# %% ../nbs/wrapper.ipynb 2
import time
import signal

# %% ../nbs/wrapper.ipynb 3
class TimeoutException(Exception):   # Custom exception class
    pass


def break_after(seconds=2):
    def timeout_handler(signum, frame):   # Custom signal handler
        raise TimeoutException
    def function(function):
        def wrapper(*args, **kwargs):
            signal.signal(signal.SIGALRM, timeout_handler)
            signal.alarm(seconds)
            try:
                res = function(*args, **kwargs)
                signal.alarm(0)      # Clear alarm
                return res
            except TimeoutException:
                print('Timeout reached ')
            return
        return wrapper
    return function
